Add type declarations for Vue 2
open-data-plan/g2plot-vue pull request #236
Opened 2021-05-10 10:51 UTC by sxzz

- chore: add types for vue2
- chore: add types declarations in package.json

2021-05-14 02:18 UTC, kagawagao requested changes

2021-05-14 02:18 UTC, kagawagao commented on package.json
> +  "types": "es/index.d.ts",
no need `types` field,  type definitions exist in every build output directory

2021-05-14 02:18 UTC, kagawagao commented on package.json
> +    "build:types2": "vue-demi-switch 2 && tsc & tsc --declarationDir ./es2",
it should be `vue-demi-switch 2 && tsc  --declarationDir ./lib2 & tsc --declarationDir ./es2`

2021-05-15 14:32 UTC, sxzz commented
Updated. Thanks.

2021-05-15 14:37 UTC, kagawagao approved these changes

2021-05-18 13:46 UTC, merged